# Generated by Django 6.1.1 on 2026-09-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_link', models.URLField()),
                ('short_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=25)),
            ],
        ),
    ]
