# Generated by Django 6.1.1 on 2026-09-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkstorage',
            name='short_link',
        ),
    ]
